# Generated by Django 4.2.7 on 2023-11-09 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_miembros', '0004_remove_persona_direccion'),
        ('gestion_metricas', '0002_distribucionacentossubcategoria_entrenador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='distribucionvolsemnxcontenidocualidad',
            name='entrenador',
            field=models.ManyToManyField(to='gestion_miembros.entrenador'),
        ),
        migrations.AddField(
            model_name='distribucionvolsemnxcontenidocualidad',
            name='grupo_etario',
            field=models.ManyToManyField(to='gestion_miembros.grupoetario'),
        ),
        migrations.AddField(
            model_name='distribucionvolsemnxcontenidocualidad',
            name='instructor',
            field=models.ManyToManyField(to='gestion_miembros.instructor'),
        ),
    ]
