# Generated by Django 4.2.7 on 2023-11-13 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_metricas', '0003_distribucionvolsemnxcontenidocualidad_entrenador_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='distribucionacentossubcategoria',
            name='instructor',
        ),
        migrations.RemoveField(
            model_name='distribucionvolsemnxcontenidocualidad',
            name='instructor',
        ),
    ]
