# Generated by Django 4.2.6 on 2023-11-01 00:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_miembros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoEtario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rango_edad', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='persona',
            name='CI',
        ),
        migrations.RemoveField(
            model_name='persona',
            name='id',
        ),
        migrations.AddField(
            model_name='atleta',
            name='continuante',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='gestion_miembros.direccion'),
        ),
        migrations.AddField(
            model_name='atleta',
            name='nuevo_ingreso',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='ocupacion_madre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='ocupacion_padre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='atleta',
            name='padres_fallecidos',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='atleta',
            name='vive_con',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='persona',
            name='genero',
            field=models.CharField(choices=[('M', 'MASCULINO'), ('F', 'FEMENINO')], default='M', max_length=10),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='municipio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='gestion_miembros.municipio'),
        ),
        migrations.CreateModel(
            name='RelacionEntrenadorGrupoEtario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entrenador', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_miembros.entrenador')),
                ('grupo_etario', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_miembros.grupoetario', to_field='rango_edad')),
            ],
        ),
        migrations.AddField(
            model_name='atleta',
            name='grupo_etario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_miembros.grupoetario'),
        ),
        migrations.AddField(
            model_name='entrenador',
            name='grupo_etario',
            field=models.ManyToManyField(through='gestion_miembros.RelacionEntrenadorGrupoEtario', to='gestion_miembros.grupoetario'),
        ),
        migrations.AddField(
            model_name='persona',
            name='ci',
            field=models.CharField(blank=True, max_length=11, primary_key=True, serialize=False, unique=True),
        ),
    ]
