# Generated by Django 4.2.6 on 2023-11-05 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_miembros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='instructor',
            name='persona',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instructor_persona', to='gestion_miembros.persona'),
        ),
    ]
