# Generated by Django 4.2.7 on 2023-11-09 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_miembros', '0002_instructor_persona'),
        ('gestion_miembros', '0002_persona_direccion'),
    ]

    operations = [
    ]
