# Generated by Django 4.2.7 on 2023-11-09 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_miembros', '0003_merge_0002_instructor_persona_0002_persona_direccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='direccion',
        ),
    ]
