# Generated by Django 4.2.7 on 2023-11-13 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_metricas', '0004_remove_distribucionacentossubcategoria_instructor_and_more'),
        ('gestion_miembros', '0004_remove_persona_direccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='edad',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.DeleteModel(
            name='Instructor',
        ),
    ]
